// // WARNING: THIS FILE IS AUTOMATICALLY GENERATED BY PIGEON.
// // DO NOT EDIT MANUALLY!
// // ------------------------------------------------------------------------
// //
// // Any changes made to this file will be destroyed on the next code generation.
// // To modify the API contracts for v2net, edit the source file:
// // pigeons/vpn_api.dart
// //
// // After making changes, run the following command:
// // make generate-vpn-api
// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.v2net

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object VpnApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class VpnStatus(val raw: Int) {
  DISCONNECTED(0),
  CONNECTING(1),
  CONNECTED(2),
  DISCONNECTING(3),
  ERROR(4);

  companion object {
    fun ofRaw(raw: Int): VpnStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VpnConfigMessage (
  val configJson: String,
  val serverId: String? = null,
  val title: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VpnConfigMessage {
      val configJson = pigeonVar_list[0] as String
      val serverId = pigeonVar_list[1] as String?
      val title = pigeonVar_list[2] as String?
      return VpnConfigMessage(configJson, serverId, title)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      configJson,
      serverId,
      title,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VpnConfigMessage
    return VpnApiPigeonUtils.deepEquals(this.configJson, other.configJson) && VpnApiPigeonUtils.deepEquals(this.serverId, other.serverId) && VpnApiPigeonUtils.deepEquals(this.title, other.title)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VpnApiPigeonUtils.deepHash(this.configJson)
    result = 31 * result + VpnApiPigeonUtils.deepHash(this.serverId)
    result = 31 * result + VpnApiPigeonUtils.deepHash(this.title)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VpnStatusMessage (
  val status: VpnStatus,
  val error: String? = null,
  val connectedAtEpochMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VpnStatusMessage {
      val status = pigeonVar_list[0] as VpnStatus
      val error = pigeonVar_list[1] as String?
      val connectedAtEpochMs = pigeonVar_list[2] as Long?
      return VpnStatusMessage(status, error, connectedAtEpochMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      status,
      error,
      connectedAtEpochMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VpnStatusMessage
    return VpnApiPigeonUtils.deepEquals(this.status, other.status) && VpnApiPigeonUtils.deepEquals(this.error, other.error) && VpnApiPigeonUtils.deepEquals(this.connectedAtEpochMs, other.connectedAtEpochMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VpnApiPigeonUtils.deepHash(this.status)
    result = 31 * result + VpnApiPigeonUtils.deepHash(this.error)
    result = 31 * result + VpnApiPigeonUtils.deepHash(this.connectedAtEpochMs)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VpnLogMessage (
  val level: String,
  val message: String,
  val source: String,
  val timestampMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VpnLogMessage {
      val level = pigeonVar_list[0] as String
      val message = pigeonVar_list[1] as String
      val source = pigeonVar_list[2] as String
      val timestampMs = pigeonVar_list[3] as Long
      return VpnLogMessage(level, message, source, timestampMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      level,
      message,
      source,
      timestampMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VpnLogMessage
    return VpnApiPigeonUtils.deepEquals(this.level, other.level) && VpnApiPigeonUtils.deepEquals(this.message, other.message) && VpnApiPigeonUtils.deepEquals(this.source, other.source) && VpnApiPigeonUtils.deepEquals(this.timestampMs, other.timestampMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VpnApiPigeonUtils.deepHash(this.level)
    result = 31 * result + VpnApiPigeonUtils.deepHash(this.message)
    result = 31 * result + VpnApiPigeonUtils.deepHash(this.source)
    result = 31 * result + VpnApiPigeonUtils.deepHash(this.timestampMs)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VpnTrafficMessage (
  val uplinkBytes: Long,
  val downlinkBytes: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VpnTrafficMessage {
      val uplinkBytes = pigeonVar_list[0] as Long
      val downlinkBytes = pigeonVar_list[1] as Long
      return VpnTrafficMessage(uplinkBytes, downlinkBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uplinkBytes,
      downlinkBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VpnTrafficMessage
    return VpnApiPigeonUtils.deepEquals(this.uplinkBytes, other.uplinkBytes) && VpnApiPigeonUtils.deepEquals(this.downlinkBytes, other.downlinkBytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VpnApiPigeonUtils.deepHash(this.uplinkBytes)
    result = 31 * result + VpnApiPigeonUtils.deepHash(this.downlinkBytes)
    return result
  }
}

/**
 * Result of a start/stop request.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VpnResult (
  val successful: Boolean,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VpnResult {
      val successful = pigeonVar_list[0] as Boolean
      val error = pigeonVar_list[1] as String?
      return VpnResult(successful, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      successful,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VpnResult
    return VpnApiPigeonUtils.deepEquals(this.successful, other.successful) && VpnApiPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VpnApiPigeonUtils.deepHash(this.successful)
    result = 31 * result + VpnApiPigeonUtils.deepHash(this.error)
    return result
  }
}
private open class VpnApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VpnStatus.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VpnConfigMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VpnStatusMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VpnLogMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VpnTrafficMessage.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VpnResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is VpnStatus -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is VpnConfigMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is VpnStatusMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is VpnLogMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is VpnTrafficMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is VpnResult -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Flutter -> native
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface VpnConnection {
  fun start(config: VpnConfigMessage, callback: (Result<VpnResult>) -> Unit)
  fun stop(callback: (Result<VpnResult>) -> Unit)
  fun getStatus(callback: (Result<VpnStatusMessage>) -> Unit)

  companion object {
    /** The codec used by VpnConnection. */
    val codec: MessageCodec<Any?> by lazy {
      VpnApiPigeonCodec()
    }
    /** Sets up an instance of `VpnConnection` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: VpnConnection?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.v2net.VpnConnection.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as VpnConfigMessage
            api.start(configArg) { result: Result<VpnResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(VpnApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(VpnApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.v2net.VpnConnection.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stop{ result: Result<VpnResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(VpnApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(VpnApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.v2net.VpnConnection.getStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getStatus{ result: Result<VpnStatusMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(VpnApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(VpnApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * native -> Flutter
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class VpnEventReceiver(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by VpnEventReceiver. */
    val codec: MessageCodec<Any?> by lazy {
      VpnApiPigeonCodec()
    }
  }
  fun onStatusChanged(messageArg: VpnStatusMessage, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.v2net.VpnEventReceiver.onStatusChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(VpnApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onLog(messageArg: VpnLogMessage, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.v2net.VpnEventReceiver.onLog$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(VpnApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onTraffic(messageArg: VpnTrafficMessage, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.v2net.VpnEventReceiver.onTraffic$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(VpnApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
