// // WARNING: THIS FILE IS AUTOMATICALLY GENERATED BY PIGEON.
// // DO NOT EDIT MANUALLY!
// // ------------------------------------------------------------------------
// //
// // Any changes made to this file will be destroyed on the next code generation.
// // To modify the API contracts for v2net, edit the source file:
// // pigeons/vpn_api.dart
// //
// // After making changes, run the following command:
// // make generate-vpn-api
// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, omit_local_variable_types, omit_obvious_local_variable_types

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Lifecycle of the VPN tunnel. The native side is the source of truth and
/// pushes every transition through [VpnEventReceiver.onStatusChanged].
enum VpnStatus {
  disconnected,
  connecting,
  connected,
  disconnecting,
  error,
}

/// Everything the native side needs to bring up a tunnel for one server.
class VpnConfigMessage {
  VpnConfigMessage({
    required this.configJson,
    this.serverId,
    this.title,
  });

  String configJson;

  String? serverId;

  String? title;

  List<Object?> _toList() {
    return <Object?>[
      configJson,
      serverId,
      title,
    ];
  }

  Object encode() {
    return _toList();  }

  static VpnConfigMessage decode(Object result) {
    result as List<Object?>;
    return VpnConfigMessage(
      configJson: result[0]! as String,
      serverId: result[1] as String?,
      title: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VpnConfigMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(configJson, other.configJson) && _deepEquals(serverId, other.serverId) && _deepEquals(title, other.title);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A status transition. [error] is only meaningful for [VpnStatus.error].
class VpnStatusMessage {
  VpnStatusMessage({
    required this.status,
    this.error,
  });

  VpnStatus status;

  String? error;

  List<Object?> _toList() {
    return <Object?>[
      status,
      error,
    ];
  }

  Object encode() {
    return _toList();  }

  static VpnStatusMessage decode(Object result) {
    result as List<Object?>;
    return VpnStatusMessage(
      status: result[0]! as VpnStatus,
      error: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VpnStatusMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(status, other.status) && _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A single log line emitted by the core (xray / tun2socks).
class VpnLogMessage {
  VpnLogMessage({
    required this.level,
    required this.message,
    required this.source,
    required this.timestampMs,
  });

  String level;

  String message;

  String source;

  int timestampMs;

  List<Object?> _toList() {
    return <Object?>[
      level,
      message,
      source,
      timestampMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static VpnLogMessage decode(Object result) {
    result as List<Object?>;
    return VpnLogMessage(
      level: result[0]! as String,
      message: result[1]! as String,
      source: result[2]! as String,
      timestampMs: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VpnLogMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(level, other.level) && _deepEquals(message, other.message) && _deepEquals(source, other.source) && _deepEquals(timestampMs, other.timestampMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Cumulative traffic counters since the tunnel came up.
class VpnTrafficMessage {
  VpnTrafficMessage({
    required this.uplinkBytes,
    required this.downlinkBytes,
  });

  int uplinkBytes;

  int downlinkBytes;

  List<Object?> _toList() {
    return <Object?>[
      uplinkBytes,
      downlinkBytes,
    ];
  }

  Object encode() {
    return _toList();  }

  static VpnTrafficMessage decode(Object result) {
    result as List<Object?>;
    return VpnTrafficMessage(
      uplinkBytes: result[0]! as int,
      downlinkBytes: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VpnTrafficMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uplinkBytes, other.uplinkBytes) && _deepEquals(downlinkBytes, other.downlinkBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Result of a start/stop request.
class VpnResult {
  VpnResult({
    required this.successful,
    this.error,
  });

  bool successful;

  String? error;

  List<Object?> _toList() {
    return <Object?>[
      successful,
      error,
    ];
  }

  Object encode() {
    return _toList();  }

  static VpnResult decode(Object result) {
    result as List<Object?>;
    return VpnResult(
      successful: result[0]! as bool,
      error: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VpnResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(successful, other.successful) && _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is VpnStatus) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is VpnConfigMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is VpnStatusMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is VpnLogMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is VpnTrafficMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is VpnResult) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : VpnStatus.values[value];
      case 130:
        return VpnConfigMessage.decode(readValue(buffer)!);
      case 131:
        return VpnStatusMessage.decode(readValue(buffer)!);
      case 132:
        return VpnLogMessage.decode(readValue(buffer)!);
      case 133:
        return VpnTrafficMessage.decode(readValue(buffer)!);
      case 134:
        return VpnResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Flutter -> native
class VpnConnection {
  /// Constructor for [VpnConnection].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  VpnConnection({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<VpnResult> start(VpnConfigMessage config) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.v2net.VpnConnection.start$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[config]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as VpnResult;
  }

  Future<VpnResult> stop() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.v2net.VpnConnection.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as VpnResult;
  }

  /// Source of truth queried on resume to re-sync the UI.
  Future<VpnStatusMessage> getStatus() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.v2net.VpnConnection.getStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as VpnStatusMessage;
  }
}

/// native -> Flutter
abstract class VpnEventReceiver {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onStatusChanged(VpnStatusMessage message);

  void onLog(VpnLogMessage message);

  void onTraffic(VpnTrafficMessage message);

  static void setUp(VpnEventReceiver? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.v2net.VpnEventReceiver.onStatusChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final VpnStatusMessage arg_message = args[0]! as VpnStatusMessage;
          try {
            api.onStatusChanged(arg_message);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.v2net.VpnEventReceiver.onLog$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final VpnLogMessage arg_message = args[0]! as VpnLogMessage;
          try {
            api.onLog(arg_message);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.v2net.VpnEventReceiver.onTraffic$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final VpnTrafficMessage arg_message = args[0]! as VpnTrafficMessage;
          try {
            api.onTraffic(arg_message);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
